const $=id=>document.getElementById(id); let state
for(const m of [3,5,7,10,15,20]){const b=document.createElement('button');b.className='preset';b.dataset.minutes=m;b.textContent=`${m} 分鐘`;b.onclick=()=>meditation.command('duration',m);$('presets').append(b)}
const set=(key,value)=>meditation.command('set',{[key]:value})
function bindCheck(id,key=id){$(id).onchange=e=>set(key,e.target.checked)}
function bindRange(id,key=id,suffix=' pt'){$(id).oninput=e=>{ $(id+'V').textContent=e.target.value+suffix; set(key,Number(e.target.value)) }}
function bindFont(id){$(id).onchange=e=>set(id,e.target.value)}
bindCheck('showClock');bindCheck('showText');bindCheck('showCountdown');bindCheck('alwaysOnTop');bindCheck('gradient');bindCheck('silent');bindCheck('musicEnabled');bindRange('clockSize');bindRange('textSize');bindRange('countdownSize');bindRange('progressSize','progressSize','%')
for(const id of ['clockFont','textFont','countdownFont'])bindFont(id)
$('clock24').onchange=e=>set('clock24',e.target.value==='true');$('progressStyle').onchange=e=>set('progressStyle',e.target.value);$('musicMode').onchange=e=>set('music',{...state.music,mode:e.target.value});$('text').oninput=e=>set('text',e.target.value);$('background').oninput=e=>set('background',e.target.value);$('background2').oninput=e=>set('background2',e.target.value)
for(const id of ['start','toggle','reset','finish'])$(id).onclick=()=>meditation.command(id);$('setDuration').onclick=()=>meditation.command('duration',Number($('custom').value));$('backgroundImage').onclick=async()=>{const f=await meditation.chooseFile('image');if(f)set('backgroundImage',f)}
const audio=$('audio');for(const kind of ['opening','music','closing']){const names={opening:'開頭磬聲',music:'背景音樂',closing:'結尾磬聲'};const div=document.createElement('div');div.innerHTML=`<div class="row"><button class="grow" data-file>${names[kind]}：選擇…</button></div><div class="muted" data-info></div><div class="row"><span>音量</span><input data-volume type="range" min="0" max="100"><span class="value" data-v></span></div><div class="row"><label><input data-in type="checkbox">靜心開始淡入</label><label><input data-out type="checkbox">靜心結束淡出</label></div>`;audio.append(div);div.querySelector('[data-file]').onclick=async()=>{if(kind==='music'&&state.music.mode==='playlist'){const files=await meditation.chooseFiles('audio');if(files.length)set('music',{...state.music,files,file:files[0]})}else{const f=await meditation.chooseFile('audio');if(f)set(kind,{...state[kind],file:f,files:kind==='music'?[f]:state[kind].files})}};div.querySelector('[data-volume]').oninput=e=>set(kind,{...state[kind],volume:Number(e.target.value)});div.querySelector('[data-in]').onchange=e=>set(kind,{...state[kind],fadeIn:e.target.checked});div.querySelector('[data-out]').onchange=e=>set(kind,{...state[kind],fadeOut:e.target.checked});div.dataset.kind=kind}
function paint(s){state=s;$('timer').textContent=s.remainingText;$('elapsed').textContent=s.elapsedText;$('status').textContent={ready:'準備完成',running:'靜心進行中',paused:'已暫停',finished:'靜心已完成'}[s.status];const isPreset=[3,5,7,10,15,20].includes(s.selectedMinutes);for(const button of document.querySelectorAll('.preset'))button.classList.toggle('active',Number(button.dataset.minutes)===s.selectedMinutes);$('custom').classList.toggle('active',!isPreset);if(!isPreset&&document.activeElement!==$('custom'))$('custom').value=s.selectedMinutes;for(const id of ['showClock','showText','showCountdown','alwaysOnTop','gradient','silent','musicEnabled'])$(id).checked=s[id];$('clock24').value=String(s.clock24);$('progressStyle').value=s.progressStyle;$('musicMode').value=s.music.mode||'single';$('text').value=s.text;$('background').value=s.background;$('background2').value=s.background2;for(const id of ['clockFont','textFont','countdownFont'])if([...$(id).options].some(o=>o.value===s[id]))$(id).value=s[id];for(const id of ['clockSize','textSize','countdownSize','progressSize']){$(id).value=s[id];$(id+'V').textContent=s[id]+(id==='progressSize'?'%':' pt')}for(const div of audio.children){const a=s[div.dataset.kind];div.querySelector('[data-volume]').value=a.volume;div.querySelector('[data-v]').textContent=a.volume+'%';div.querySelector('[data-in]').checked=a.fadeIn;div.querySelector('[data-out]').checked=a.fadeOut;const count=div.dataset.kind==='music'?(a.files?.length||(+!!a.file)):0;div.querySelector('[data-info]').textContent=div.dataset.kind==='music'?(a.mode==='playlist'?`播放清單：${count} 首（換曲不中斷）`:'單首循環（循環時不中斷）'):''}}
function updateNow(){$('now').textContent=new Date().toLocaleTimeString('zh-TW',{hour12:false})}
updateNow();setInterval(updateNow,500)
meditation.onState(paint);meditation.getState().then(paint);meditation.getAddresses().then(addresses=>{const container=$('addresses');container.replaceChildren();for(const address of addresses){const url=`http://${address}:4747/`;const row=document.createElement('div');row.className='address-row';const label=document.createElement('span');label.textContent=`${address}:4747`;const button=document.createElement('button');button.textContent='開啟';button.onclick=()=>meditation.openBrowser(url);row.append(label,button);container.append(row)}})
meditation.getFonts().then(fonts=>{for(const id of ['clockFont','textFont','countdownFont']){$(id).replaceChildren(...fonts.map(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;option.style.fontFamily=name==='系統預設字體'?'system-ui':name;return option}));if(state)$(id).value=state[id]||'系統預設字體'}})
