const $=id=>document.getElementById(id),stage=$('stage');let state,lastStatus,drag
function fileURL(p){return p||''}
function clockText(){const d=new Date();return state.clock24?d.toLocaleTimeString('zh-TW',{hour12:false}):d.toLocaleTimeString('zh-TW',{hour12:true})}
function position(el,p){el.style.left=p.x*100+'%';el.style.top=(1-p.y)*100+'%'}
function play(kind,onEnded){if(state.silent){onEnded?.();return}const a=$(kind),cfg=state[kind];if(!cfg.file){onEnded?.();return}a.src=fileURL(cfg.file);a.volume=cfg.fadeIn?0:cfg.volume/100;a.currentTime=0;a.onended=()=>onEnded?.();a.ontimeupdate=()=>{if(cfg.fadeOut&&a.duration&&a.duration-a.currentTime<2)a.volume=Math.max(0,(a.duration-a.currentTime)/2*cfg.volume/100)};a.play().catch(()=>onEnded?.());if(cfg.fadeIn){let i=0;const t=setInterval(()=>{i++;a.volume=Math.min(cfg.volume/100,i/20*cfg.volume/100);if(i>=20)clearInterval(t)},100)}}
let musicIndex=0,musicFadeTimer
function musicFiles(){const files=state.music.files?.length?state.music.files:[state.music.file].filter(Boolean);return state.music.mode==='playlist'?files:files.slice(0,1)}
function playMusic(resume=false){if(state.silent||!state.musicEnabled)return;const a=$('music'),files=musicFiles();if(!files.length)return;if(resume&&!a.getAttribute('src'))resume=false;if(!resume){musicIndex=0;a.src=fileURL(files[0]);a.currentTime=0}a.loop=state.music.mode!=='playlist';a.onended=()=>{if(state.music.mode!=='playlist'||state.status!=='running')return;musicIndex=(musicIndex+1)%files.length;a.src=fileURL(files[musicIndex]);a.volume=state.music.volume/100;a.play().catch(()=>{})};a.volume=resume||!state.music.fadeIn?state.music.volume/100:0;a.play().catch(()=>{});if(!resume&&state.music.fadeIn){clearInterval(musicFadeTimer);let i=0;musicFadeTimer=setInterval(()=>{i++;a.volume=Math.min(state.music.volume/100,i/20*state.music.volume/100);if(i>=20)clearInterval(musicFadeTimer)},100)}}
function fadeMusicThenClosing(){const a=$('music');if(a.paused){play('closing');return}if(!state.music.fadeOut){a.pause();play('closing');return}let i=20;const t=setInterval(()=>{i--;a.volume=Math.max(0,i/20*state.music.volume/100);if(i<=0){clearInterval(t);a.pause();play('closing')}},100)}
function audioTransitions(s){if(lastStatus!==s.status){if(s.status==='running'&&(lastStatus==='ready'||lastStatus==='finished'))play('opening',()=>{if(state.status==='running')playMusic()});if(s.status==='paused')$('music').pause();if(lastStatus==='paused'&&s.status==='running')playMusic(true);if(s.status==='finished')fadeMusicThenClosing();lastStatus=s.status}}
function applyLiveAudioSettings(previous,s){if(!previous)return;if(s.silent&&!previous.silent){clearInterval(musicFadeTimer);for(const id of ['opening','music','closing'])$(id).pause();return}if(!s.silent&&previous.silent&&s.status==='running'&&s.musicEnabled){playMusic(true);return}if(s.musicEnabled!==previous.musicEnabled&&s.status==='running'&&!s.silent){clearInterval(musicFadeTimer);if(s.musicEnabled)playMusic(true);else $('music').pause()}if(s.music.volume!==previous.music.volume&&!$('music').paused)$('music').volume=s.music.volume/100}
function applyFonts(s){const family=name=>!name||name==='系統預設字體'?'system-ui':name;$('clock').style.fontFamily=family(s.clockFont);$('text').style.fontFamily=family(s.textFont);$('countdown').style.fontFamily=family(s.countdownFont)}
function paint(s){const previous=state;state=s;applyLiveAudioSettings(previous,s);audioTransitions(s);stage.style.background=s.gradient?`linear-gradient(135deg,${s.background},${s.background2})`:s.background;stage.style.backgroundImage=s.backgroundImage?`url("${fileURL(s.backgroundImage)}")`:s.gradient?`linear-gradient(135deg,${s.background},${s.background2})`:'';$('clock').hidden=!s.showClock;$('clock').textContent=clockText();$('clock').style.fontSize=s.clockSize+'px';position($('clock'),s.clockPosition);$('text').hidden=!s.showText;$('text').textContent=s.text;$('text').style.fontSize=s.textSize+'px';$('text').style.color=s.textColor;position($('text'),s.textPosition);$('countdown').hidden=!s.showCountdown;$('progress').hidden=!s.showCountdown;$('countdown').textContent=s.remainingText;$('countdown').style.fontSize=s.countdownSize+'px';position($('countdown'),s.countdownPosition);const p=$('progress'),size=s.progressSize;p.className='progress '+s.progressStyle;p.style.setProperty('--p',Math.max(0,Math.min(1,s.progress)));p.style.setProperty('--start',s.progressStart);p.style.setProperty('--end',s.progressEnd);p.style.left=s.countdownPosition.x*100+'%';p.style.top=(1-s.countdownPosition.y)*100+'%';p.style.width=size+'vw';p.style.height=s.progressStyle==='ring'?size+'vw':'8px'}
setInterval(()=>{if(state&&state.showClock)$('clock').textContent=clockText()},500)
for(const [id,target] of [['clock','clock'],['text','text'],['countdown','countdown']]){$(id).addEventListener('pointerdown',e=>{e.preventDefault();drag={target};stage.classList.add('dragging');$(id).setPointerCapture(e.pointerId);meditation.dragPosition(target,null,'begin')});$(id).addEventListener('pointermove',e=>{if(!drag||drag.target!==target)return;let x=e.clientX/stage.clientWidth,y=1-e.clientY/stage.clientHeight;for(const n of [.25,.5,.75]){if(Math.abs(x-n)<.012)x=n;if(Math.abs(y-n)<.02)y=n}meditation.dragPosition(target,{x:Math.max(.03,Math.min(.97,x)),y:Math.max(.05,Math.min(.95,y))},'move')});$(id).addEventListener('pointerup',()=>{if(!drag)return;drag=null;stage.classList.remove('dragging');meditation.dragPosition(target,null,'end')})}
let backgroundDrag
stage.addEventListener('pointerdown',e=>{if(e.button!==0||e.target!==stage)return;backgroundDrag=e.pointerId;stage.setPointerCapture(e.pointerId);meditation.dragParticipantWindow(null,'begin')})
stage.addEventListener('pointermove',e=>{if(backgroundDrag!==e.pointerId)return;meditation.dragParticipantWindow(null,'move')})
const endBackgroundDrag=e=>{if(backgroundDrag!==e.pointerId)return;backgroundDrag=null;meditation.dragParticipantWindow(null,'end')}
stage.addEventListener('pointerup',endBackgroundDrag)
stage.addEventListener('pointercancel',endBackgroundDrag)
stage.addEventListener('dblclick',e=>{e.preventDefault();meditation.toggleParticipantFullscreen()})
meditation.onState(s=>{paint(s);applyFonts(s)});meditation.getState().then(s=>{paint(s);applyFonts(s)})
